### PR TITLE
fix: wait for filesize to be more than 0 if waitUntilSaved is set

### PR DESCRIPTION
**Pull request by sondremare**
This change is [Reviewable](https://reviewable.io/reviews/edtechfoundry/react-native-image-picker/2)

### CODE REVIEW

**Comment by kennethlynne** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java, line 14 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ57bWK-DwxcCX6W-6:-KdQ57bWK-DwxcCX6W-7:b2nhknf) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java#L14)):*
> ```Java
>     public interface FileSizeAsyncResponse {
>         void processFinish(Boolean result);
> ```

OCD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2)*

**Comment by kennethlynne** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java, line 10 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ5B5alvr1Oa4hYbNN:-KdQ5B5alvr1Oa4hYbNO:boxi0um) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java#L10)):*
> ```Java
> public class CheckFileSizeAsyncTask extends AsyncTask<Void, Void, Boolean> {
> 
>     public static final String TAG = "ImagePicker";
> ```

react native image pikker

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2)*

**Comment by kennethlynne** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java, line 28 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ5ZLDWfwpA4wwcYwK:-KdQ5ZLDWfwpA4wwcYwL:b-qofp9g) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java#L28)):*
> ```Java
>     protected Boolean doInBackground(Void... params) {
>         File file = new File(this.filePath);
>         for (int i = 0; i < 30; i++) { // We try for 30 seconds;
> ```

configurable max timeout?

---

*[android/src/main/java/com/imagepicker/ImagePickerModule.java, line 68 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ5bnPx_tYUUI0gk12:-KdQ5bnPx_tYUUI0gk13:b-y20256) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/ImagePickerModule.java#L68)):*
> ```Java
>   static final int REQUEST_LAUNCH_VIDEO_CAPTURE = 13004;
> 
>   public static final String TAG = "ImagePicker";
> ```

move into a separate file with this constant, or wrap logging in a separate helper that adds this prefix

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2)*

**Comment by kennethlynne** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[android/src/main/java/com/imagepicker/ImagePickerModule.java, line 831 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ6QZSyc3BvN59KTvd:-KdQ6QZSyc3BvN59KTve:b-7hsr56) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/ImagePickerModule.java#L831)):*
> ```Java
>         }).execute();
>       } else {
>         // we do nothing, as image handling has already been handled in the constructor
> ```

video

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2)*

**Comment by nadeesha** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-:-KdQFLx7HaUucXe9GtES:bnfp4nl)*

**Comment by sondremare** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java, line 10 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ5B5alvr1Oa4hYbNN:-KdQSkzb0Drr_6tsF-Q9:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java#L10)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

react native image pikker
</blockquote></details>

Done.

---

*[android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java, line 14 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ57bWK-DwxcCX6W-6:-KdQSlSYw_DKybCSTsHK:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java#L14)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

OCD
</blockquote></details>

Done.

---

*[android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java, line 28 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ5ZLDWfwpA4wwcYwK:-KdQSn7cUfhjfjmdKRGf:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/CheckFileSizeAsyncTask.java#L28)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

configurable max timeout?
</blockquote></details>

Done.

---

*[android/src/main/java/com/imagepicker/ImagePickerModule.java, line 68 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ5bnPx_tYUUI0gk12:-KdQSnsmeZ4Y5rRbTxda:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/ImagePickerModule.java#L68)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

move into a separate file with this constant, or wrap logging in a separate helper that adds this prefix
</blockquote></details>

Done.

---

*[android/src/main/java/com/imagepicker/ImagePickerModule.java, line 831 at r1](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-KdQ6QZSyc3BvN59KTvd:-KdQSoO3otURkiRSV10D:b-896fix) ([raw file](https://github.com/edtechfoundry/react-native-image-picker/blob/7cbb46b3b2ef0948e74e0536677496db50d6a784/android/src/main/java/com/imagepicker/ImagePickerModule.java#L831)):*
<details><summary><i>Previously, kennethlynne (Kenneth Lynne) wrote…</i></summary><blockquote>

video
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2)*

**Comment by kennethlynne** [comment]
:lgtm:

---

Reviewed 1 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/edtechfoundry/react-native-image-picker/2#-:-KdQTQo1Et-Fh19VrrjC:bnfp4nl)*

**Pull request merged**
